# Config for Google App Engine


# >>> gcloud app deploy --project lorrgs


service: default
runtime: python39
entrypoint: gunicorn -b :$PORT "lorgs.app:create_app()"
# entrypoint: flask run --host=0.0.0.0 --port=$PORT

includes:
  - deploy_variables.yaml

handlers:
  - url: /static
    static_dir: lorgs/static

  - url: /.*
    script: auto

