# Config for Google App Engine


# >>> gcloud app deploy --project lorrgs

service: default
runtime: python39

entrypoint: >
  gunicorn
  -b :$PORT
  --timeout=240
  --workers 4
  --worker-class uvicorn.workers.UvicornWorker
  "lorgs.app:create_app()"

# longer timeout for the api calls that load data
# entrypoint: uvicorn --port $PORT --factory "lorgs.app:create_app"
# entrypoint: flask run --host=0.0.0.0 --port=$PORT


includes:
  - deploy_variables.yaml

handlers:
  - url: /static
    static_dir: lorgs/static

  - url: /.*
    script: auto

