steps:


# Build SCSS
- name: "python:3"
  entrypoint: python3
  args: ["-m", "pip", "install", "-t", ".", "pysassc"]
- name: 'python:3'
  entrypoint: python3
  args: ["-m", "pysassc", "--style=compact", "lorgs/templates/scss/main.scss", "lorgs/static/_generated/style.css"]


# Deploy the APP
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
  timeout: "1600s"
  env:
  - 'LORGS_CONFIG_NAME=lorgs.config.ProductionConfig'
  - 'WCL_CLIENT_ID=${_WCL_CLIENT_ID}'
  - 'WCL_CLIENT_SECRET=${_WCL_CLIENT_SECRET}'
  - 'MONGO_URI=${_MONGO_URI}'
  - 'REDIS_URL=${_REDIS_URL}'

