steps:


# Build SCSS
- name: "python:3"
  entrypoint: python3
  args: ["-m", "pip", "install", "-t", , ".", pysass"]
- name: "python:3"
  entrypoint: 'mkdir'
  args: ["-p", "lorgs/static/_generated"]
- name: 'python:3'
  entrypoint: python3
  args: ["-m", "pysassc", "--style=compact", "lorgs/templates/scss/main.scss", "lorgs/static/_generated/style.css"]

# add sensible config
- name: 'gcr.io/cloud-builders/gsutil'
  args: ["cp", "gs://lorgs-config/deploy_variables.yaml", '.']
  waitFor: ['-']  # The '-' indicates that this step begins immediately.

# Deploy the APP
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
  timeout: "1600s"
  env:
  - 'LORGS_CONFIG_NAME=lorgs.config.ProductionConfig'
  - 'WCL_CLIENT_ID=${_WCL_CLIENT_ID}'
  - 'WCL_CLIENT_SECRET=${_WCL_CLIENT_SECRET}'
  - 'MONGO_URI=${_MONGO_URI}'
  - 'REDIS_URL=${_REDIS_URL}'

