version: '3.7'

services:

  # nginx:
  #   build: ./nginx
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - web
  #   volumes:
  #     - ./lorgs:/data/lorgs

  # main web app (flask)
  web:
    image: lorgs
    build: .
    # command: echo "disabled"  # disable this, so we can run flask local
    command: gunicorn
      --bind 0.0.0.0:5000
      "lorgs.app:create_app()"
      --worker-tmp-dir /dev/shm
      --workers=4
    ports:
      - "${PORT:-5010}:5000"  # todo: change to expose to only expose internal
    env_file:
      - .env

    environment:
      REDIS_URL: redis://redis:6379
      FLASK_APP: "lorgs/app:create_app()"

    depends_on:
      # - db
      - redis

  # background worker (celery)
  # worker:
  #   <<: *env
  #   image: lorgs
  #   command: celery
  #     --app=lorgs.celery
  #     worker
  #     --loglevel=INFO
  #     --concurrency=4
  #   depends_on:
  #     - db
  #     - redis
  #     - web

  # redis
  redis:
    image: redis
    ports:
      - 6379:6379 # expose the redis port, so we can connect locally

  # database
  # db:
  #   image: postgres:13.2-alpine
  #   restart: always
  #   environment:
  #     POSTGRES_USER: ${MYSQL_USER}
  #     POSTGRES_PASSWORD: ${MYSQL_PASSWORD}
  #     POSTGRES_DB: ${MYSQL_DATABASE}
  #   ports:
  #   - 5432:5432
  #   volumes:
  #     - data-db:/var/lib/postgresql/data


volumes:
  data-db:

