version: '3.7'
services:

  page:
    build: .
    command: echo "none"

    # command: flask run --host=0.0.0.0
    # command: gunicorn
    #   --bind 0.0.0.0:5000
    #   --worker-tmp-dir /dev/shm
    #   --workers=1
    #   "tvcSkyhooks.app:create_app()"
    ports:
      - "5010:5000"
      # SQLALCHEMY_DATABASE_URI: sqlite://
    environment:

      # dev env
      FLASK_APP: "lorgs/app:create_app()"
      FLASK_ENV: development
      DEBUG: "true"

  redis:
    image: redis
    ports:
    - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    # restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"


# docker run -it --network="host" windok/redis-browser bash


#
# docker run --rm -p 8081:8081 --env REDIS_HOST=lorgs-redis rediscommander/redis-commander

