version: '3.7'
services:

  web:
    build: .
    # command: echo "none"
    command: gunicorn
      --bind 0.0.0.0:5000
      --worker-tmp-dir /dev/shm
      --workers=4
      "lorgs.app:create_app()"
    ports:
      - "5010:5000"
    env_file:
      - .env
    environment:
      # dev env
      FLASK_APP: "lorgs/app:create_app()"
      # FLASK_ENV: development
      # DEBUG: "true"
      REDIS_URL: redis://redis:6379
    # volumes:
    #   - ./lorgs:/app/lorgs
    depends_on:
      - redis

  celery_worker:
    build: .
    command: celery
      --app=lorgs.tasks.celery
      worker
      --loglevel=INFO
      --concurrency=16
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379
      # CELERY_BROKER_URL: redis://redis:6379/0
      # CELERY_RESULT_BACKEND: redis://redis:6379/0
      # CELERY_BROKER_URL: redis://redis:6379/0
      # CELERY_RESULT_BACKEND: redis://redis:6379/0
      # REDIS_HOST: redis
    depends_on:
      - web
      - redis

    # volumes:
    #   - ./lorgs:/app/lorgs

  redis:
    image: redis
    ports:
    - "6379:6379"


  # celery_dashboard:
  #   build: .
  #   command:  flower --app=lorgs.tasks.celery --port=5555 --broker=redis://redis:6379/0
  #   ports:
  #     - 5556:5555
  #   environment:
  #     - FLASK_DEBUG=1
  #   depends_on:
  #     - web
  #     - redis
  #     - celery_worker

# docker run -it --network="host" windok/redis-browser bash


#
# docker run --rm -p 8081:8081 --env REDIS_HOST=lorgs-redis rediscommander/redis-commander

